### ISSUE TITLE
unable to use "decrypt.sh"

### ISSUE THREAD

**Issue by etiennespieser** [louis845/SimpleFolderEncryption#1]
Hi @louis845,

Nice and handy script to perform encryption with GnuPG.

The command:
```
./encrypt.sh --input_folder_path="./test" --output_path="./secret_test"
```
prompts a message for the user to enter a password, and I was able to encrypt a folder with this technique. However, the command, 
```
./encrypt.sh --input_folder_path="./test" --output_path="./secret_test" --password="toto"
```
failed, which may be an unwanted behavior...

Another point, is that none of the commands,
```
./decrypt.sh --input_path="./secret_test" --output_path="./test_cracked"
```
or,
```
./decrypt.sh --input_path="./secret_test" --output_path="./test_cracked" --password="toto"
```
did work... Any idea why?

**Comment by louis845** [comment]
Thanks for your comments! The password option is mainly to automate the encryption and decryption of multiple folders with scripts, and it is not expected for a string to be used as a password. For the decryption command, the argument should be `--output_folder_path`.

I have updated the README.md to provide a more detailed description.
